name: Linting

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Read Node.js version from .node-version
        run: echo "NODE_VERSION=$(cat .node-version)" >> $GITHUB_OUTPUT
        id: node-version

      - name: Install PNPM
        uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ steps.node-version.outputs.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.node-version.outputs.NODE_VERSION }}
          cache: "pnpm"

      - name: Install dependencies 🔧
        run: pnpm install --frozen-lockfile

      - name: Lint 🔍
        run: pnpm lint
